import type { School, Product, UniformKit, Category } from "@/types"

export const MOCK_SCHOOLS: School[] = [
  {
    id: "s1",
    name: "Delhi Public School",
    slug: "delhi-public-school",
    logo_url: "/schools/dps.png",
    location: "Greater Noida",
    city: "Greater Noida",
    state: "Uttar Pradesh",
    is_active: true,
    created_at: "2024-01-01",
  },
  {
    id: "s2",
    name: "Ryan International School",
    slug: "ryan-international-school",
    logo_url: "/schools/ryan.png",
    location: "Noida",
    city: "Noida",
    state: "Uttar Pradesh",
    is_active: true,
    created_at: "2024-01-01",
  },
  {
    id: "s3",
    name: "Amity International School",
    slug: "amity-international-school",
    logo_url: "/schools/amity.png",
    location: "Sector 46, Gurugram",
    city: "Gurugram",
    state: "Haryana",
    is_active: true,
    created_at: "2024-01-01",
  },
  {
    id: "s4",
    name: "Kendriya Vidyalaya",
    slug: "kendriya-vidyalaya",
    logo_url: "/schools/kv.png",
    location: "Sector 12, Delhi",
    city: "Delhi",
    state: "Delhi",
    is_active: true,
    created_at: "2024-01-01",
  },
  {
    id: "s5",
    name: "Modern School",
    slug: "modern-school",
    logo_url: "/schools/modern.png",
    location: "Barakhamba Road, Delhi",
    city: "Delhi",
    state: "Delhi",
    is_active: true,
    created_at: "2024-01-01",
  },
  {
    id: "s6",
    name: "Springdales School",
    slug: "springdales-school",
    logo_url: "/schools/springdales.png",
    location: "Pusa Road, Delhi",
    city: "Delhi",
    state: "Delhi",
    is_active: true,
    created_at: "2024-01-01",
  },
]

export const MOCK_CATEGORIES: Category[] = [
  { id: "c1", name: "Uniform", slug: "uniform", sort_order: 1 },
  { id: "c2", name: "Accessories", slug: "accessories", sort_order: 2 },
  { id: "c3", name: "Footwear", slug: "footwear", sort_order: 3 },
  { id: "c4", name: "Bags", slug: "bags", sort_order: 4 },
  { id: "c5", name: "Winter Wear", slug: "winter-wear", sort_order: 5 },
  { id: "c6", name: "Gifts & Merchandise", slug: "gifts", sort_order: 6 },
]

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "DPS White School Shirt",
    slug: "dps-white-school-shirt",
    description: "Premium cotton white shirt with school embroidered logo.",
    category_id: "c1",
    category: MOCK_CATEGORIES[0],
    price: 499,
    discount_price: 449,
    gender: "boys",
    rating: 4.5,
    review_count: 128,
    is_active: true,
    images: [
      { id: "i1", product_id: "p1", url: "/products/shirt-white.jpg", sort_order: 0 },
    ],
    variants: [
      { id: "v1", product_id: "p1", size: "28", stock: 15, sku: "DPS-SHT-28" },
      { id: "v2", product_id: "p1", size: "30", stock: 20, sku: "DPS-SHT-30" },
      { id: "v3", product_id: "p1", size: "32", stock: 10, sku: "DPS-SHT-32" },
      { id: "v4", product_id: "p1", size: "34", stock: 8, sku: "DPS-SHT-34" },
      { id: "v5", product_id: "p1", size: "36", stock: 0, sku: "DPS-SHT-36" },
    ],
    created_at: "2024-01-01",
  },
  {
    id: "p2",
    name: "DPS Navy Blue Trousers",
    slug: "dps-navy-blue-trousers",
    description: "Comfortable navy blue school trousers with adjustable waist.",
    category_id: "c1",
    category: MOCK_CATEGORIES[0],
    price: 699,
    discount_price: 649,
    gender: "boys",
    rating: 4.3,
    review_count: 95,
    is_active: true,
    images: [
      { id: "i2", product_id: "p2", url: "/products/trousers-navy.jpg", sort_order: 0 },
    ],
    variants: [
      { id: "v6", product_id: "p2", size: "28", stock: 12, sku: "DPS-TRS-28" },
      { id: "v7", product_id: "p2", size: "30", stock: 18, sku: "DPS-TRS-30" },
      { id: "v8", product_id: "p2", size: "32", stock: 24, sku: "DPS-TRS-32" },
      { id: "v9", product_id: "p2", size: "34", stock: 7, sku: "DPS-TRS-34" },
    ],
    created_at: "2024-01-01",
  },
  {
    id: "p3",
    name: "DPS Navy Blazer",
    slug: "dps-navy-blazer",
    description: "School blazer with DPS crest embroidery on chest pocket.",
    category_id: "c5",
    category: MOCK_CATEGORIES[4],
    price: 1499,
    discount_price: 1299,
    gender: "boys",
    rating: 4.7,
    review_count: 203,
    is_active: true,
    images: [
      { id: "i3", product_id: "p3", url: "/products/blazer-navy.jpg", sort_order: 0 },
    ],
    variants: [
      { id: "v10", product_id: "p3", size: "32", stock: 8, sku: "DPS-BLZ-32" },
      { id: "v11", product_id: "p3", size: "34", stock: 14, sku: "DPS-BLZ-34" },
      { id: "v12", product_id: "p3", size: "36", stock: 10, sku: "DPS-BLZ-36" },
      { id: "v13", product_id: "p3", size: "38", stock: 5, sku: "DPS-BLZ-38" },
    ],
    created_at: "2024-01-01",
  },
  {
    id: "p4",
    name: "DPS V-Neck Sweater",
    slug: "dps-vneck-sweater",
    description: "Woollen V-neck sweater with school stripe.",
    category_id: "c5",
    category: MOCK_CATEGORIES[4],
    price: 799,
    gender: "unisex",
    rating: 4.4,
    review_count: 167,
    is_active: true,
    images: [
      { id: "i4", product_id: "p4", url: "/products/sweater.jpg", sort_order: 0 },
    ],
    variants: [
      { id: "v14", product_id: "p4", size: "S", stock: 20, sku: "DPS-SWT-S" },
      { id: "v15", product_id: "p4", size: "M", stock: 25, sku: "DPS-SWT-M" },
      { id: "v16", product_id: "p4", size: "L", stock: 18, sku: "DPS-SWT-L" },
      { id: "v17", product_id: "p4", size: "XL", stock: 10, sku: "DPS-SWT-XL" },
    ],
    created_at: "2024-01-01",
  },
  {
    id: "p5",
    name: "DPS School Tie",
    slug: "dps-school-tie",
    description: "Official DPS striped school tie.",
    category_id: "c2",
    category: MOCK_CATEGORIES[1],
    price: 199,
    gender: "unisex",
    rating: 4.2,
    review_count: 88,
    is_active: true,
    images: [
      { id: "i5", product_id: "p5", url: "/products/tie.jpg", sort_order: 0 },
    ],
    variants: [
      { id: "v18", product_id: "p5", size: "Standard", stock: 50, sku: "DPS-TIE-STD" },
    ],
    created_at: "2024-01-01",
  },
  {
    id: "p6",
    name: "Leather School Belt",
    slug: "leather-school-belt",
    description: "Black leather belt with silver buckle.",
    category_id: "c2",
    category: MOCK_CATEGORIES[1],
    price: 149,
    gender: "unisex",
    rating: 4.1,
    review_count: 56,
    is_active: true,
    images: [
      { id: "i6", product_id: "p6", url: "/products/belt.jpg", sort_order: 0 },
    ],
    variants: [
      { id: "v19", product_id: "p6", size: "S", stock: 30, sku: "BELT-S" },
      { id: "v20", product_id: "p6", size: "M", stock: 40, sku: "BELT-M" },
      { id: "v21", product_id: "p6", size: "L", stock: 25, sku: "BELT-L" },
    ],
    created_at: "2024-01-01",
  },
  {
    id: "p7",
    name: "White Cotton School Socks",
    slug: "white-cotton-school-socks",
    description: "Pack of 3 white cotton ankle socks.",
    category_id: "c2",
    category: MOCK_CATEGORIES[1],
    price: 99,
    gender: "unisex",
    rating: 4.0,
    review_count: 312,
    is_active: true,
    images: [
      { id: "i7", product_id: "p7", url: "/products/socks.jpg", sort_order: 0 },
    ],
    variants: [
      { id: "v22", product_id: "p7", size: "S (3-5)", stock: 60, sku: "SOCKS-S" },
      { id: "v23", product_id: "p7", size: "M (5-8)", stock: 80, sku: "SOCKS-M" },
      { id: "v24", product_id: "p7", size: "L (8-11)", stock: 45, sku: "SOCKS-L" },
    ],
    created_at: "2024-01-01",
  },
  {
    id: "p8",
    name: "Black School Shoes",
    slug: "black-school-shoes",
    description: "Durable black leather school shoes with non-slip sole.",
    category_id: "c3",
    category: MOCK_CATEGORIES[2],
    price: 899,
    discount_price: 799,
    gender: "boys",
    rating: 4.6,
    review_count: 241,
    is_active: true,
    images: [
      { id: "i8", product_id: "p8", url: "/products/shoes-black.jpg", sort_order: 0 },
    ],
    variants: [
      { id: "v25", product_id: "p8", size: "3", stock: 10, sku: "SHO-3" },
      { id: "v26", product_id: "p8", size: "4", stock: 15, sku: "SHO-4" },
      { id: "v27", product_id: "p8", size: "5", stock: 18, sku: "SHO-5" },
      { id: "v28", product_id: "p8", size: "6", stock: 12, sku: "SHO-6" },
      { id: "v29", product_id: "p8", size: "7", stock: 8, sku: "SHO-7" },
    ],
    created_at: "2024-01-01",
  },
  {
    id: "p9",
    name: "DPS School Bag",
    slug: "dps-school-bag",
    description: "Sturdy 30L school backpack with laptop compartment.",
    category_id: "c4",
    category: MOCK_CATEGORIES[3],
    price: 1199,
    discount_price: 999,
    gender: "unisex",
    rating: 4.8,
    review_count: 189,
    is_active: true,
    images: [
      { id: "i9", product_id: "p9", url: "/products/bag-school.jpg", sort_order: 0 },
    ],
    variants: [
      { id: "v30", product_id: "p9", size: "Standard", stock: 35, sku: "DPS-BAG-STD" },
    ],
    created_at: "2024-01-01",
  },
]

export const MOCK_UNIFORM_KIT: UniformKit = {
  id: "k1",
  school_id: "s1",
  name: "DPS Class 6 Boys Summer Uniform",
  class_level: "Class 6",
  gender: "boys",
  uniform_type: "summer",
  items: [
    { id: "ki1", kit_id: "k1", product: MOCK_PRODUCTS[0], is_required: true, sort_order: 1 },
    { id: "ki2", kit_id: "k1", product: MOCK_PRODUCTS[1], is_required: true, sort_order: 2 },
    { id: "ki3", kit_id: "k1", product: MOCK_PRODUCTS[4], is_required: true, sort_order: 3 },
    { id: "ki4", kit_id: "k1", product: MOCK_PRODUCTS[5], is_required: true, sort_order: 4 },
    { id: "ki5", kit_id: "k1", product: MOCK_PRODUCTS[6], is_required: true, sort_order: 5 },
    { id: "ki6", kit_id: "k1", product: MOCK_PRODUCTS[7], is_required: false, sort_order: 6 },
    { id: "ki7", kit_id: "k1", product: MOCK_PRODUCTS[8], is_required: false, sort_order: 7 },
  ],
}

export const CLASS_LEVELS = [
  "Nursery", "LKG", "UKG",
  "Class 1", "Class 2", "Class 3", "Class 4", "Class 5",
  "Class 6", "Class 7", "Class 8", "Class 9", "Class 10",
  "Class 11", "Class 12",
]

export const INDIAN_STATES = [
  "Andhra Pradesh", "Assam", "Bihar", "Chhattisgarh", "Delhi",
  "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand",
  "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur",
  "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Punjab",
  "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura",
  "Uttar Pradesh", "Uttarakhand", "West Bengal",
]
