[build]
  command   = "npm run build"
  publish   = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Next.js Image Optimization
[[redirects]]
  from = "/_next/image*"
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200
